name: yapt
description: "Yet Another Phasmophobia Tracker"

publish_to: 'none'
 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

#---------------------- Packages ----------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.18.1
  logger: ^2.0.1
  http: ^1.1.0
  url_launcher: ^6.1.12
  provider: ^6.1.2

  # Icons
  iconsax: ^0.0.8
  ionicons: ^0.2.2
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.5
  #get_storage: ^2.1.1

#---------------------- ./ End of Packages ----------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

#---------------------- LOCAL ASSETS ----------------------#
  assets:
   - assets/logos/
   - assets/icons/
   - assets/images/on_boarding_images/
   - assets/icons/evidence/

#---------------------- LOCAL FONTS ----------------------#
  fonts:
    - family: lazy_dog
      fonts:
        - asset: assets/fonts/lazy_dog.ttf
          weight: 300
    - family: October_Crow
      fonts:
        - asset: assets/fonts/October_Crow.ttf
          weight: 300
    - family: Yahfie
      fonts:
        - asset: assets/fonts/Yahfie-Light.ttf
          weight: 300
        - asset: assets/fonts/Yahfie-Normal.ttf
          weight: 500
        - asset: assets/fonts/Yahfie-Heavy.ttf
          weight: 600



